=== Proger125/JavaProjects/Up_12/out/production/Up_12/gems.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/gems"
        xmlns:tns="http://www.example.org/gems"
        elementFormDefault="qualified" >
    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="Gem">
        <sequence>
            <element name="name" type="string"/>
            <element name="preciousness" type="tns:Preciousness" />
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="creation-date" type="gYearMonth"/>
        </sequence>
        <attribute name="id" use="required" type="tns:Id" />
        <attribute name="weight" use="optional" default="1" type="tns:Weight"/>
    </complexType>

    <complexType name="Natural-gem">
        <complexContent>
            <extension base="tns:Gem">
                <sequence>
                    <element name="extraction-place" type="tns:Extraction-place" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Artificial-gem">
        <complexContent>
            <extension base="tns:Gem">
                <sequence>
                    <element name="growing-time" type="tns:Growing-time" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <simpleType name="Preciousness">
        <restriction base="string">
            <enumeration value="Precious"/>
            <enumeration value="SemiPrecious"/>
        </restriction>
    </simpleType>

    <simpleType name="Id">
        <restriction base="ID">
            <pattern value="\w{1,15}"/>
        </restriction>
    </simpleType>

    <simpleType name="Weight">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="3000"/>
        </restriction>
    </simpleType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="color" type="string"/>
            <element name="transparency" type="tns:Transparency" />
            <element name="edge-amount" type="tns:Edge-amount" />
        </sequence>
    </complexType>

    <simpleType name="Transparency">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="Edge-amount">
        <restriction base="positiveInteger">
            <minInclusive value="4"/>
            <maxInclusive value="15"/>
        </restriction>
    </simpleType>

    <simpleType name="Extraction-place">
        <restriction base="string">
            <enumeration value="Africa"/>
            <enumeration value="Asia"/>
            <enumeration value="Europe"/>
            <enumeration value="North-America"/>
            <enumeration value="South-America"/>
            <enumeration value="Siberia"/>
        </restriction>
    </simpleType>

    <simpleType name="Growing-time">
        <restriction base="positiveInteger">
            <minInclusive value="100"/>
            <maxInclusive value="1000"/>
        </restriction>
    </simpleType>


    <element name="gem" type="tns:Gem" abstract="true"/>
    <element name="natural-gem" type="tns:Natural-gem" substitutionGroup="tns:gem"/>
    <element name="artificial-gem" type="tns:Artificial-gem" substitutionGroup="tns:gem"/>
</schema>

=== Proger125/JavaProjects/Up_12/resources/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><gems xmlns="http://www.example.org/gems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/gems gems.xsd"><natural-gem id="g1" weight="5"><extraction-place>AFRICA</extraction-place><name>Diamond</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Yellow</color><transparency>80</transparency><edge-amount>4</edge-amount></visual-parameters><creation-date>2021-03</creation-date></natural-gem><natural-gem id="g2" weight="0"><extraction-place>ASIA</extraction-place><name>Ruby</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Red</color><transparency>90</transparency><edge-amount>13</edge-amount></visual-parameters><creation-date>2020-12</creation-date></natural-gem><natural-gem id="g3" weight="0"><extraction-place>NORTH_AMERICA</extraction-place><name>Sapphire</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Blue</color><transparency>65</transparency><edge-amount>15</edge-amount></visual-parameters><creation-date>2020-08</creation-date></natural-gem><natural-gem id="g7" weight="0"><extraction-place>AFRICA</extraction-place><name>Topaz</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Pale blue</color><transparency>75</transparency><edge-amount>12</edge-amount></visual-parameters><creation-date>2002-10</creation-date></natural-gem><natural-gem id="g8" weight="0"><extraction-place>NORTH_AMERICA</extraction-place><name>Citrine</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>White</color><transparency>96</transparency><edge-amount>8</edge-amount></visual-parameters><creation-date>1973-10</creation-date></natural-gem><natural-gem id="g11" weight="0"><extraction-place>SIBERIA</extraction-place><name>Heliodor</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>Golden yellow</color><transparency>59</transparency><edge-amount>13</edge-amount></visual-parameters><creation-date>1987-11</creation-date></natural-gem><natural-gem id="g12" weight="0"><extraction-place>SIBERIA</extraction-place><name>Opal</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>Orange</color><transparency>57</transparency><edge-amount>8</edge-amount></visual-parameters><creation-date>1989-03</creation-date></natural-gem><natural-gem id="g13" weight="0"><extraction-place>AFRICA</extraction-place><name>Andalusite</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>Grey</color><transparency>86</transparency><edge-amount>5</edge-amount></visual-parameters><creation-date>2005-04</creation-date></natural-gem><artificial-gem id="g4" weight="8"><growing-time>500</growing-time><name>Artificial Diamond</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Blue</color><transparency>97</transparency><edge-amount>4</edge-amount></visual-parameters><creation-date>2018-06</creation-date></artificial-gem><artificial-gem id="g5" weight="0"><growing-time>900</growing-time><name>Artificial Ruby</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Burgundy</color><transparency>76</transparency><edge-amount>12</edge-amount></visual-parameters><creation-date>2002-03</creation-date></artificial-gem><artificial-gem id="g6" weight="2"><growing-time>480</growing-time><name>Artificial Sapphire</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Grey</color><transparency>92</transparency><edge-amount>14</edge-amount></visual-parameters><creation-date>1978-07</creation-date></artificial-gem><artificial-gem id="g9" weight="0"><growing-time>527</growing-time><name>Artificial Tanzanite</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Blue</color><transparency>99</transparency><edge-amount>6</edge-amount></visual-parameters><creation-date>1923-10</creation-date></artificial-gem><artificial-gem id="g10" weight="0"><growing-time>784</growing-time><name>Artificial Aquamarine</name><preciousness>PRECIOUS</preciousness><visual-parameters><color>Greenish blue</color><transparency>68</transparency><edge-amount>13</edge-amount></visual-parameters><creation-date>1968-06</creation-date></artificial-gem><artificial-gem id="g14" weight="0"><growing-time>368</growing-time><name>Artificial Tourmaline</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>Brown</color><transparency>75</transparency><edge-amount>15</edge-amount></visual-parameters><creation-date>1965-02</creation-date></artificial-gem><artificial-gem id="g15" weight="0"><growing-time>459</growing-time><name>Demantoid</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>Green</color><transparency>35</transparency><edge-amount>4</edge-amount></visual-parameters><creation-date>2001-03</creation-date></artificial-gem><artificial-gem id="g16" weight="0"><growing-time>759</growing-time><name>Artificial Tsavorite</name><preciousness>SEMIPRECIOUS</preciousness><visual-parameters><color>Dark green</color><transparency>26</transparency><edge-amount>9</edge-amount></visual-parameters><creation-date>1999-05</creation-date></artificial-gem></gems>

=== Proger125/JavaProjects/Up_12/resources/gems_incorrect.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/gems"
        xsi:schemaLocation="http://www.example.org/gems gems.xsd">

    <natural-gem id="g1" weight="5">
        <name>Diamond</name>
        <preciousness>Precious</preciousness>
        <visual-parameters>
            <color>Yellow</color>
            <transparency>80</transparency>
            <edge-amount>6</edge-amount>
        </visual-parameters>
        <creation-date>2021-03</creation-date>
        <extraction-place>Africa</extraction-place>
    </natural-gem>
    <natural-gem id="g2">
        <name>Ruby</name>
        <preciousness>Precious</preciousness>
        <visual-parameters>
            <color>Red</color>
            <transparency>90</transparency>
            <edge-amount>13</edge-amount>
        </visual-parameters>
        <creation-date>2020-12</creation-date>
        <extraction-place>Asia</extraction-place>
    </natural-gem>
    <natural-gem id="g3">
        <name>Sapphire</name>
        <preciousness>Precious</preciousness>
        <visual-parameters>
            <color>Blue</color>
            <transparency>65</transparency>
            <edge-amount>15</edge-amount>
        </visual-parameters>
        <creation-date>2020-08</creation-date>
        <extraction-place>North-America</extraction-place>
    </natural-gem>
    <artificial-gem id="g4" weight="8">
        <name>Artificial Diamond</name>
        <preciousness>Precious</preciousness>
        <visual-parameters>
            <color>Blue</color>
            <transparency>-97</transparency>
            <edge-amount>4</edge-amount>
        </visual-parameters>
        <creation-date>2018-06</creation-date>
        <growing-time>500</growing-time>
    </artificial-gem>
    <artificial-gem id="g5">
        <name>Artificial Ruby</name>
        <preciousness>Precious</preciousness>
        <visual-parameters>
            <color>Burgundy</color>
            <transparency>76</transparency>
            <edge-amount>12</edge-amount>
        </visual-parameters>
        <creation-date>2002-03</creation-date>
        <growing-time>900</growing-time>
    </artificial-gem>
    <artificial-gem id="g6" weight="2">
        <name>Artificial Sapphire</name>
        <preciousness>Precious</preciousness>
        <visual-parameters>
            <color>Grey</color>
            <transparency>92</transparency>
            <edge-amount>14</edge-amount>
        </visual-parameters>
        <creation-date>1978-07</creation-date>
        <growing-time>480</growing-time>
    </artificial-gem>

</gems>
